ipl/urls.py
from django.urls import path
from . import views

app_name = 'ipl'

urlpatterns = [
    path('', views.index, name='index'),
    path('api/matches_per_year/', views.matches_per_year, name='matches_per_year'),
    path('api/wins_per_team_per_year/', views.wins_per_team_per_year, name='wins_per_team_per_year'),
    path('api/extra_runs_conceded_2016/', views.extra_runs_conceded_2016, name='extra_runs_conceded_2016'),
    path('api/top_economical_bowlers_2015/', views.top_economical_bowlers_2015, name='top_economical_bowlers_2015'),

    path('matches_per_year_chart/', views.matches_per_year_chart, name='matches_per_year_chart'),
    path('wins_per_team_per_year_chart/', views.wins_per_team_per_year_chart, name='wins_per_team_per_year_chart'),
    path('extra_runs_conceded_2016_chart/', views.extra_runs_conceded_2016_chart,
         name='extra_runs_conceded_2016_chart'),
    path('top_economical_bowlers_2015_chart/', views.top_economical_bowlers_2015_chart,
         name='top_economical_bowlers_2015_chart'),
]

ipl_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ipl.urls')),
    path('admin/', admin.site.urls),
    # path('ipl/', include('ipl.urls')),
]

ipl/models.py
from django.db import models

# Create your models here.


class Match(models.Model):
    id = models.AutoField(primary_key=True)
    season = models.IntegerField()
    city = models.CharField(max_length=100, null=True)
    date = models.DateField()
    team1 = models.CharField(max_length=100)
    team2 = models.CharField(max_length=100)
    toss_winner = models.CharField(max_length=100)
    toss_decision = models.CharField(max_length=100)
    result = models.CharField(max_length=100)
    dl_applied = models.IntegerField()  # 0 or 1
    winner = models.CharField(max_length=100, null=True)
    wins_by_runs = models.IntegerField()
    wins_by_wickets = models.IntegerField()
    player_of_match = models.CharField(max_length=100, null=True)
    venue = models.CharField(max_length=100)
    umpire1 = models.CharField(max_length=100, null=True)
    umpire2 = models.CharField(max_length=100, null=True)
    umpire3 = models.CharField(max_length=100, null=True)

    def __str__(self):
        return "Season: " + str(self.season) + " - " + self.team1 + " vs " + self.team2


class Delivery(models.Model):
    id = models.AutoField(primary_key=True)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    inning = models.IntegerField()
    batting_team = models.CharField(max_length=100)
    bowling_team = models.CharField(max_length=100)
    over = models.IntegerField()
    ball = models.IntegerField()
    batsman = models.CharField(max_length=100)
    non_striker = models.CharField(max_length=100)
    bowler = models.CharField(max_length=100)
    is_super_over = models.IntegerField()  # 0 or 1
    wide_runs = models.IntegerField()
    bye_runs = models.IntegerField()
    legbye_runs = models.IntegerField()
    noball_runs = models.IntegerField()
    penalty_runs = models.IntegerField()
    batsman_runs = models.IntegerField()
    extra_runs = models.IntegerField()
    total_runs = models.IntegerField()
    player_dismissed = models.CharField(max_length=100, null=True)
    dismissal_kind = models.CharField(max_length=100, null=True)
    fielder = models.CharField(max_length=100, null=True)

    def __str__(self):
        return "Match: " + str(self.match.id) + " - " + self.batsman + " vs " + self.bowler

ipl/views.py
# import json
# from django.http import HttpResponse
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Count, Sum
from ipl.models import Match, Delivery

# Create your views here.
# Number of matches played per year for all the years in IPL.


def index(request):
    return render(request, 'pages/index.html')


def matches_per_year(request):
    result = Match.objects.values('season').annotate(matches=Count('id')).order_by('season')
    return JsonResponse(list(result), safe=False)


def wins_per_team_per_year(request):
    matches = Match.objects.values('season', 'winner').exclude(winner='').annotate(
        wins=Count('winner')).order_by('season')

    wins_per_team = {}
    for match in matches:
        season = match['season']
        team = match['winner']
        wins = match['wins']

        if season not in wins_per_team:
            wins_per_team[season] = {}

        wins_per_team[season][team] = wins

    return JsonResponse(wins_per_team, safe=False)
    # json_data = json.dumps(wins_per_team, indent=2)
    # return HttpResponse(json_data, content_type='application/json')


def extra_runs_conceded_2016(request):
    result = Delivery.objects.filter(match__season=2016).values('bowling_team').annotate(
        extra_runs_conceded=Sum('extra_runs')).order_by('bowling_team')
    return JsonResponse(list(result), safe=False)

# def extra_runs_conceded_2016(request):
#     deliveries = Delivery.objects.filter(match__season=2016).values('bowling_team').annotate(
#       extra_runs=Sum('extra_runs'))
#     extra_runs = {}
#     for delivery in deliveries:
#         team = delivery['bowling_team']
#         runs = delivery['extra_runs']
#         extra_runs[team] = runs

#     return JsonResponse(extra_runs, safe=False)


# def top_economical_bowlers_2015(request):
#     bowler_stats = Delivery.objects.filter(match__season=2015).values('bowler').annotate(
#         total_runs=Sum('total_runs'),
#         balls=Count('id'),
#         overs=Count('id') / 6,
#         extra_balls=Count('id') % 6,
#     )

#     for stats in bowler_stats:
#         stats['economy'] = stats['total_runs'] / (stats['overs'] + stats['extra_balls'] / 6)

#     bowler_stats = sorted(bowler_stats, key=lambda stats: stats['economy'])[:10]
#     return JsonResponse(bowler_stats, safe=False)


def top_economical_bowlers_2015(request):
    deliveries = Delivery.objects.filter(match__season=2015).values('bowler').annotate(
        runs=Sum('total_runs') - Sum('bye_runs') - Sum('legbye_runs'),
        balls=Count('ball') - (Count('ball') % 6)).order_by('runs', 'balls')

    bowlers = {}
    for delivery in deliveries:
        bowler = delivery['bowler']
        runs = delivery['runs']
        balls = delivery['balls']
        economy = round(runs / balls * 6, 2)
        bowlers[bowler] = economy

    # top 10 bowlers
    bowlers = dict(sorted(bowlers.items(), key=lambda item: item[1])[:10])
    return JsonResponse(bowlers, safe=False)


def matches_per_year_chart(request):
    return render(request, 'pages/matches_per_year_chart.html')


def wins_per_team_per_year_chart(request):
    return render(request, 'pages/wins_per_team_per_year_chart.html')


def extra_runs_conceded_2016_chart(request):
    return render(request, 'pages/extra_runs_conceded_2016_chart.html')


def top_economical_bowlers_2015_chart(request):
    return render(request, 'pages/top_economical_bowlers_2015_chart.html')

ipl/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap 4.3.1 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <title>IPL Project</title>
    <!-- HighCharts -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
</head>
<body>
    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="row">
          <div class="col-lg-12 m-auto text-center">{% block content %}{% endblock %}</div>
        </div>
    </div>

    {% include 'partials/_footer.html' %}
</body>
</html>

ipl/templates/pages/extra_runs_conceded_2016_chart.html
{% extends 'base.html' %}

{% block content %}
    <h1>Problem 3</h1>
    <div id="extra-runs-conceded-2016" class="mt-4"></div>

    {% include 'partials/_back_button.html' %}
    <hr>
    <div class="m-4">
        <a href="{% url 'ipl:extra_runs_conceded_2016' %}" target="_blank">View API ↵</a>
    </div>
    {% load static %}
    <script src="{% static 'js/problem3.js' %}"></script>
{% endblock %}

ipl/templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="card mt-3">
    <div class="card-body">
        <h1>Welcome to IPL Project</h1>
        <img src="{% static 'img/ipl_logo.png' %}" alt="" width="50%">
        <p>IPL Data Analysis</p>
        <a href="{% url 'ipl:index' %}" class="btn btn-dark">
            ⇓ GO DOWN ⇓
        </a>
    </div>
</div>

<div class="row d-flex justify-content-between mb-5">
    <div class="card my-4 col-md-6">
        <div class="card-body bg-dark text-light p-5">
            <h4 class="card-title">Matches Played Per Year Chart</h4>
            <p class="card-text">HighCharts for Number of matches played per year for all the years in IPL</p>
            <a href="{% url 'ipl:matches_per_year_chart' %}" class="btn btn-primary">View Chart »</a>
        </div>
    </div>
    <div class="card my-4 col-md-6">
        <div class="card-body bg-dark text-light p-5">
            <h4 class="card-title">Wins Per Team Per Year Chart</h4>
            <p class="card-text">Highcharts for Number of matches won per team per year in IPL</p>
            <a href="{% url 'ipl:wins_per_team_per_year_chart' %}" class="btn btn-primary">View Chart »</a>
        </div>
    </div>
    <div class="card my-4 col-md-6">
        <div class="card-body bg-dark text-light p-5">
            <h4 class="card-title">Extra Runs Conceded In 2016 Chart</h4>
            <p class="card-text">HighCharts for Extra runs conceded per team in the year 2016</p>
            <a href="{% url 'ipl:extra_runs_conceded_2016_chart' %}" class="btn btn-primary">View Chart »</a>
        </div>
    </div>
    <div class="card my-4 col-md-6">
        <div class="card-body bg-dark text-light p-5">
            <h4 class="card-title">Top Economical Bowlers In 2015 Chart</h4>
            <p class="card-text">HighCharts for Top 10 economical bowlers in the year 2015</p>
            <a href="{% url 'ipl:top_economical_bowlers_2015_chart' %}" class="btn btn-primary">View Chart »</a>
        </div>
    </div>

</div>

{% endblock %}

ipl/templates/pages/matches_per_year_chart.html
{% extends 'base.html' %}

{% block content %}
    <h1>Problem 1</h1>
    <div id="matches-per-year" class="mt-4"></div>
    
    {% include 'partials/_back_button.html' %}
    <hr>
    <div class="m-4">
        <a href="{% url 'ipl:matches_per_year' %}" target="_blank">View API ↵</a>
    </div>
    {% load static %}
    <script src="{% static 'js/problem1.js' %}"></script>
{% endblock %}

ipl/templates/pages/top_economical_bowlers_2015_chart.html
{% extends 'base.html' %}

{% block content %}
    
    <h1>Problem 4</h1>
    <div id="top-economical-bowlers-2015" class="mt-4"></div>

    {% include 'partials/_back_button.html' %}
    <hr>
    <div class="m-4">
        <a href="{% url 'ipl:top_economical_bowlers_2015' %}" target="_blank">View API ↵</a>
    </div>
    {% load static %}
    <script src="{% static 'js/problem4.js' %}"></script>
{% endblock %}

ipl/templates/pages/wins_per_team_per_year_chart.html
{% extends 'base.html' %}

{% block content %}
    <h1>Problem 2</h1>
    <div id="wins-per-team-per-year" class="mt-4"></div>

    {% include 'partials/_back_button.html' %}
    <hr>
    <div class="m-4">
        <a href="{% url 'ipl:wins_per_team_per_year' %}" target="_blank">View API ↵</a>
    </div>
    {% load static %}
    <script src="{% static 'js/problem2.js' %}"></script>
{% endblock %}

ipl/templates/partials/_back_button.html
<div class="mt-5">
    <a href="{% url 'ipl:index' %}" class="btn btn-info px-4" style="font-size: 1.5rem;">« Back</a>
</div>

ipl/templates/partials/_footer.html
<footer class="page-footer font-small bg-info text-light">
    <div class="footer-copyright text-center py-3">© 2023 Copyright:
        <small>Created By - </small><a href="/" class="text-light text-decoration-none"> Anirban Das</a>
    </div>
</footer>

ipl/templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a href="/" class="navbar-brand">IPL PROJECT</a>
        <img src="{% static 'img/ipl_logo.png' %}" alt="IPL Logo" width="15%" height="15%">
    </div>
</nav>